version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server --requirepass yourpassword
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/postgresql/data

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    # links:
    #   - docker-postgres
    #   - docker-redis
    depends_on:
      - db
      - redis

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - '.:/app'
    env_file:
      - '.docker.env'

volumes:
  redis-data:
  db-data:

